# first_time_join_message - 첫 입장 메시지
# join_message - 입장 메시지
# leave_message - 퇴장 메시지

# 플레이어의 이름을 가져오려면 [NAME]을 사용해 주세요.
# 사용 예시:
# join_message: "[NAME]님이 접속하셨습니다."
# leave_message: "[NAME]님이 퇴장하셨습니다."
# 색을 사용하시려면 마인크래프트 색상 코드를 사용해 주세요.
# 사용 예시:
# join_message: "&e&l[NAME]&f님이 접속하셨습니다."

first_time_join_message: "&e&l[NAME]&f님이 서버에 처음 접속하셨습니다. 모두 환영해 주세요!"
join_message: "&e&l[NAME]&f님이 접속하셨습니다. 어서오세요!"
leave_message: "&e&l[NAME]&f님이 퇴장하셨습니다. 안녕히 가세요!"
shift_right_click_command: "kill %player%"  # %player%는 쉬프트+우클릭한 사람의 닉네임입니다! "ex : kill %player%"로 하게되면 쉬프트+우클릭으로 타인을 죽일 수 있습니다.