# first_time_join_message - 첫 입장 메시지
# join_message - 입장 메시지
# leave_message - 퇴장 메시지

# 메시지 기능은 PlaceholderAPI를 지원합니다.
# 색을 사용하시려면 마인크래프트 색상 코드를 사용해 주세요.
# 사용 예시:
# join_message: "&e&l환영합니다!"

#쉬프트+우클릭 명령어에서 쉬프트+우클릭을 사용한 플레이어의 닉네임을 불러오려면 %player%를 통해 불러올 수 있습니다.
# 사용 예시:
# shift_right_click_command: "msg Hello, %player%!"
#쉬프트+우클릭 기능을 사용할 월드 이름 리스트를 enable_world에 입력해 주세요.

first_time_join_message: "(첫 입장 메시지)"
join_message: "(입장 메시지)"
leave_message: "(퇴장 메시지)"
title: ""
subtitle: ""
fadeIn: 0
stay: 0
fadeOut: 0