name: UtilTool
version: '${project.version}'
main: net.teamuni.playerjoinandleave.UtilTool
api-version: 1.17
softdepend: [PlaceholderAPI]
commands:
  utiltool:
    permission: utiltool.reload
  spawn:
    permission: utiltool.spawn
  tmvhs:
    permission: utiltool.spawn
  스폰:
    permission: utiltool.spawn
  넴주:
    permission: utiltool.spawn
  setspawn:
    permission: utiltool.setspawn
  채팅청소:
    permission: utiltool.mychatclear
  전체채팅청소:
    permission: utiltool.allchatclear
  확성기:
    permission: utiltool.broadcaster
  귓:
    permission: utiltool.whisper
  귓속말:
    permission: utiltool.whisper
  rnlt:
    permission: utiltool.whisper
  rnltthrakf:
    permission: utiltool.whisper
  r:
    permission: utiltool.whisper
  m:
    permission: utiltool.whisper
  msg:
    permission: utiltool.whisper
  w:
    permission: utiltool.whisper
  whisper:
    permission: utiltool.whisper
permissions:
  utiltool.reload:
    default: op
  utiltool.spawn:
    default: true
  utiltool.setspawn:
    default: op
  utiltool.mychatclear:
    default: true
  utiltool.allchatclear:
    default: op
  utiltool.broadcaster:
    default: true
  utiltool.whisper:
    default: true
