name: UtilTool
version: '${project.version}'
main: net.teamuni.playerjoinandleave.UtilTool
api-version: 1.17
softdepend: [PlaceholderAPI]
commands:
  utiltool:
    permission: utiltool.reload
  spawn:
    permission: utiltool.spawn
    aliases: [tmvhs, 스폰, 넴주]
  setspawn:
    permission: utiltool.setspawn
  채팅청소:
    permission: utiltool.mychatclear
  전체채팅청소:
    permission: utiltool.allchatclear
  확성기:
    permission: utiltool.broadcaster
  whisper:
    permission: utiltool.whisper
    aliases: [귓, 귓속말, rnlt, rnltthrakf, r, m, msg, w]
  잠수:
    permission: utiltool.movetoafk
permissions:
  utiltool.reload:
    default: op
  utiltool.spawn:
    default: true
  utiltool.setspawn:
    default: op
  utiltool.mychatclear:
    default: true
  utiltool.allchatclear:
    default: op
  utiltool.broadcaster:
    default: true
  utiltool.whisper:
    default: true
  utiltool.movetoafk:
    default: true
