name: UtilTool
version: '${project.version}'
main: net.teamuni.playerjoinandleave.UtilTool
api-version: 1.17
softdepend: [PlaceholderAPI]
commands:
  utiltool:
    permission: utiltool.reload
  spawn:
    permission: utiltool.spawn
  setspawn:
    permission: utiltool.setspawn
  채팅청소:
    permission: utiltool.mychatclear
  전체채팅청소:
    permission: utiltool.allchatclear
permissions:
  utiltool.reload:
    default: op
  utiltool.spawn:
    default: true
  utiltool.setspawn:
    default: op